const GENZ_DICTIONARY = {
  "SLAY": "to do something amazingly or look really good",
  "BET": "means yes or okay, like agreement",
  "FR": "short for for real, being honest",
  "NO CAP": "no lie, telling the truth",
  "CAP": "a lie or something fake",
  "RIZZ": "charisma, ability to flirt",
  "DELULU": "being delusional in a funny way",
  "GYATT": "reaction to seeing someone attractive",
  "SIGMA": "a lone wolf or alpha type vibe",
  "BASED": "unbothered, staying true to yourself",
  "STAN": "to be a super fan of someone",
  "SIMP": "someone who does too much for their crush",
  "BRUH": "expression of disbelief or annoyance",
  "BUSSIN": "really good, usually about food",
  "ATE": "performed well, did amazing",
  "ATE AND LEFT NO CRUMBS": "did perfectly with no mistakes",
  "MID": "average, not impressive",
  "TOUCH GRASS": "go outside, stop being online too much",
  "RATIO": "when a reply gets more likes than the original post",
  "PRESSED": "annoyed or upset over something small",
  "DRIP": "cool outfit or style",
  "GOAT": "greatest of all time",
  "LOWKEY": "a little bit, secretly",
  "HIGHKEY": "definitely, openly",
  "SUS": "suspicious or shady",
  "ITS GIVING": "describing the vibe or energy of something",
  "BIG YIKES": "really embarrassing",
  "VIBE CHECK": "testing the mood of someone or a group",
  "YEET": "throw something with force",
  "VALID": "cool, correct, or acceptable",
  "ICK": "sudden turn-off when dating",
  "SHOOK": "surprised or shocked",
  "BUILT DIFFERENT": "unique, better than others",
  "MAIN CHARACTER": "acting like the star of the story",
  "FERAL": "wild or out of control behavior",
  "SHEESH": "expression of disbelief or amazement",
  "FLEX": "showing off",
  "GHOSTED": "when someone suddenly stops talking to you",
  "LIT": "fun, exciting, or hype",
  "POOKIE": "cute nickname for someone you love",
  "BOP": "a really good song",
  "PERIODT": "used to end a statement with confidence",
  "SAVAGE": "someone who does something bold or ruthless",
  "SIDE EYE": "used to show disapproval or shade",
  "DEADASS": "seriously, no joke",
  "FYP": "for you page on TikTok",
  "TEA": "gossip or drama",
  "SPILLING TEA": "sharing gossip",
  "SIS": "calling someone girl or friend",
  "QUEEN": "compliment for a girl doing great",
  "KING": "compliment for a guy doing great",
  "W": "a win or success",
  "L": "a loss or failure",
  "SALTY": "bitter or annoyed",
  "MOOD": "something relatable",
  "CHAD": "a stereotypically confident guy",
  "SOFT LAUNCH": "subtly posting about a relationship",
  "HARD LAUNCH": "officially showing off a relationship",
  "GATEKEEP": "not sharing info so it stays exclusive",
  "GASLIGHT": "manipulating someone into doubting reality",
  "GIRLBOSS": "a confident, ambitious woman",
  "NPC": "acting boring or robotic, like a background character",
  "CAUGHT IN 4K": "caught doing something bad clearly",
  "WILDIN": "acting crazy or out of pocket",
  "BADDIE": "confident and attractive person",
  "CRYING RN": "something is so funny it makes you cry",
  "GLOW UP": "transformation for the better",
  "CLOUT": "influence or attention online",
  "IN MY BAG": "focused and doing really well",
  "REAL": "something relatable or true",
  "MOTHER": "queen, someone iconic or respected",
  "MOTHER IS MOTHERING": "when someone is doing their best perfectly",
  "FATHERLESS BEHAVIOR": "reckless or questionable actions",
  "BFFR": "be for real",
  "SNATCHED": "looking really good, usually about outfits",
  "WIG": "expression when something is shocking",
  "OOMF": "one of my followers",
  "SMH": "shaking my head, disappointment",
  "NGL": "not gonna lie",
  "IDC": "i dont care",
  "IYKYK": "if you know you know",
  "POV": "point of view, common TikTok trend",
  "CANCELLED": "when someone is socially rejected",
  "ERA": "a phase or aesthetic in someone’s life",
  "EGIRL": "girl with online alternative aesthetic",
  "EBOY": "boy with online alternative aesthetic",
  "CORECORE": "emotional aesthetic edit trend",
  "DOOMSCROLLING": "endlessly scrolling bad news online",
  "BRAINROT": "content so dumb it rots your brain",
  "GOOFY AHH": "silly, cringe, or funny",
  "FANUM TAX": "inside joke from a streamer, taking food from friends",
  "GYATT DAMN": "reaction to seeing someone attractive",
  "AURA CHECK": "testing someone’s vibe or energy",
  "GRIPPY SOCKS VACATION": "slang for going to a mental hospital",
  "RED FLAG": "warning sign in dating or behavior",
  "GREEN FLAG": "good sign in dating or behavior",
  "YELLOW FLAG": "small warning sign",
  "DEVIOUS LICK": "stealing something and bragging online",
  "NPC ENERGY": "boring or predictable behavior",
  "CAUGHT LACKING": "unprepared or embarrassed",
  "SLUMPED": "tired, knocked out, or asleep",
  "ZESTY": "acting flamboyant or sassy",
  "SNACC": "someone who looks attractive like a snack"
};

export default GENZ_DICTIONARY;